name: Python Package

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04-arm
    container:
      image: centos:7

    steps:
    - name: Run a command
      run: |
          set -x
          uname -a
          cat /etc/os-release
          lscpu
          mkdir /etc/yum.repos.d/bak
          mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/bak
          echo -e "[OS]\nname=OS\nbaseurl=https://vault.centos.org/altarch/7.9.2009/os/aarch64\nenabled=1\ngpgcheck=0" > /etc/yum.repos.d/centos-vault.repo
          cat /etc/yum.repos.d/centos-vault.repo
          yum -y install git
          git clone https://github.com/lsjhw/OmniAdaptor.git
          cd OmniAdaptor/omnihelper
          python -V
          python3 -V
