name: Python Package

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04-arm
    container:
      image: centos:7

    steps:
    - name: Run a command
      run: uname -a && cat /etc/os-release && cat /etc/yum.repo.d/* && whoami && yum install git && git clone https://github.com/lsjhw/OmniAdaptor.git
